# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N blast_bold
#$ -o blast_bold.log
#$ -m bea
#
# ----------------Modules------------------------- #
module load bioinformatics/blast
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
blastn -db /scratch/dbs/blast/bold/bold_blast_2023_01_20 \
       -query random_barcode.fasta \
       -max_target_seqs 20 \
       -outfmt "6 qseqid sseqid pident length qcovs evalue" \
       -out blast_bold_results.tsv
#
echo = `date` job $JOB_NAME done
