# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=32G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N blast_ncbi_coi
#$ -o blast_ncbi_coi.log
#$ -m bea
#
# ----------------Modules------------------------- #
module load bioinformatics/blast
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
blastn -db /scratch/meyerc/custom_coi_blast/2021_07_23/coi_filtered \
       -query random_barcode.fasta \
       -max_target_seqs 20 \
       -outfmt "6 qseqid sseqid staxid ssciname pident length qcovs evalue" \
       -out blast_ncbi_coi_results.tsv
#
echo = `date` job $JOB_NAME done
